import INDEX from "../data/boards/index.json";

/**
 * Every Keychron keyboard the app knows (generated by scripts/generate_from_qmk.py from Keychron's
 * firmware: one per VIA definition, so ANSI/ISO/JIS, knob and RGB/white variants are separate, each
 * with its own USB product id). The index is small and always loaded; a board's full data (layout,
 * LED map, stock keymap) is loaded when it's needed.
 */

export type LightingKind = "rgb" | "white" | "none";

export interface BoardInfo {
  /** File name in src/data/boards, e.g. "v6_8k_iso_encoder". */
  id: string;
  /** VIA's name, e.g. "Keychron V6 8K ISO Knob". */
  name: string;
  vid: number;
  pid: number;
  rows: number;
  cols: number;
  encoders: number;
  /** QMK keyboard path, e.g. "keychron/v6_8k/iso_encoder" (null when Keychron's tree lacks it). */
  firmware: string | null;
  /** RGB matrix, white LED matrix, or none. */
  lighting: LightingKind;
  /** Keychron's Mix RGB (and Per Key RGB) effects. */
  mix: boolean;
  /** QMK's bootloader name, e.g. "at32-dfu" (`BOOTLOADER_USB` gives its USB id). */
  bootloader?: string | null;
}

/** A key as VIA's layout draws it (units of a 1u key; rotated keys turn `r` degrees around rx, ry). */
export interface RawKey {
  row: number;
  col: number;
  x: number;
  y: number;
  w: number;
  h: number;
  /** Second rectangle (ISO Enter, big-ass Enter…), relative to x/y. */
  x2?: number;
  y2?: number;
  w2?: number;
  h2?: number;
  r?: number;
  rx?: number;
  ry?: number;
  encoder?: number;
}

export interface BoardData {
  id: string;
  name: string;
  vid: number;
  pid: number;
  matrix: { rows: number; cols: number };
  encoders: number;
  firmware: string | null;
  lighting: LightingKind;
  /** VIA's effect list: [name, id]. */
  effects: Array<[string, number]>;
  /** Which effect ids use the speed (from the VIA definition's showIf rules). */
  speedEffects: number[];
  /** Which effect ids use the colour (from the VIA definition's showIf rules). */
  colorEffects: number[];
  mix: boolean;
  /** The board's own keys (VIA's customKeycodes: entry i is QK_KB_0 + i), with their QMK names. */
  customKeycodes: Array<{ name: string; label: string; title: string }>;
  /** k_rgb_matrix_center: the effects' middle on QMK's 224 × 64 grid. */
  center: [number, number];
  keys: RawKey[];
  /** g_led_config: the key over each LED, its position on the 224 × 64 grid, and its flags. */
  leds: Array<{ key: string; x: number; y: number; flags: number }>;
  /** Keychron's stock keymap: key names per layer, in `keys` order, and each knob's per layer. */
  keymap: {
    defaultLayer: number;
    layers: string[][];
    encoders: string[][][];
  } | null;
}

/** The USB id each bootloader shows up with (`usb.rs` `BOOTLOADERS`). */
export const BOOTLOADER_USB: Record<string, [vid: number, pid: number]> = {
  "stm32-dfu": [0x0483, 0xdf11],
  "at32-dfu": [0x2e3c, 0xdf11],
  "wb32-dfu": [0x342d, 0xdfa0],
  "apm32-dfu": [0x314b, 0x0106],
};

export const BOARDS: BoardInfo[] = INDEX as BoardInfo[];
const byId = new Map(BOARDS.map((b) => [b.id, b]));

export const boardInfo = (
  id: string | null | undefined,
): BoardInfo | undefined => (id ? byId.get(id) : undefined);
export const boardByUsb = (vid: number, pid: number) =>
  BOARDS.find((b) => b.vid === vid && b.pid === pid);

/** A board's full data (a separate chunk per board in the app). */
export async function loadBoard(id: string): Promise<BoardData> {
  // Vite turns this into one lazy import per file; only called in the app, not in node tests.
  const files = import.meta.glob<BoardData>(
    ["../data/boards/*.json", "!../data/boards/index.json"],
    { import: "default" },
  );
  const load = files[`../data/boards/${id}.json`];
  if (!load) throw new Error(`No keyboard "${id}" in this version of the app.`);
  return load();
}
