#!/usr/bin/env python3
"""Regenerate src/qmk/keycodes.generated.ts and src/data/boards/ (every Keychron keyboard: layout,
matrix, knobs, lighting and effects, LED map, stock keymap) from a checkout of
https://github.com/Keychron/qmk_firmware (branch 2025q3; a sparse one with keyboards/keychron is enough).

Usage: python3 scripts/generate_from_qmk.py /path/to/qmk_firmware
"""
import json
import re
import sys
from pathlib import Path

QMK = Path(sys.argv[1] if len(sys.argv) > 1 else "../qmk_firmware")
OUT = Path(__file__).resolve().parent.parent / "src"

# ---------------------------------------------------------------- keycodes
header = (QMK / "quantum/keycodes.h").read_text()
values: dict[str, int] = {}
for name, val in re.findall(r"^\s+([A-Z][A-Z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+),", header, re.M):
    values[name] = int(val, 16)
for name, target in re.findall(r"^\s+([A-Z][A-Z0-9_]*)\s*=\s*([A-Z][A-Z0-9_]*),", header, re.M):
    if target in values:
        values[name] = values[target]

# Keychron custom keycodes (QK_KB_0 ...), only the unconditional ones.
kb_base = values["QK_KB"]
for i, name in enumerate(["KC_LOPTN", "KC_ROPTN", "KC_LCMMD", "KC_RCMMD", "KC_MCTRL",
                          "KC_LNPAD", "KC_TASK", "KC_FILE", "KC_SNAP", "KC_CTANA"]):
    values[name] = kb_base + i
values["KC_SIRI"] = kb_base + 10  # follows KC_CTANA when lock-screen keys are disabled

# US shifted names (KC_TILD = S(KC_GRAVE)…): not keycodes (the app refuses them from users, they
# mislead on other layouts), but stock keymaps use them, so they're resolved there to values.
us_shifted: dict[str, int] = {}
us = (QMK / "quantum/keymap_extras/keymap_us.h").read_text()
for name, target in re.findall(r"^#define\s+(KC_\w+)\s+S\((KC_\w+)\)", us, re.M):
    if target in values:
        us_shifted[name] = 0x0200 | values[target]
for name, target in re.findall(r"^#define\s+(KC_\w+)\s+(KC_\w+)\s*(?://.*)?$", us, re.M):
    if target in us_shifted and name not in us_shifted:
        us_shifted[name] = us_shifted[target]

# Range markers are not keycodes users should see.
skip = re.compile(r"^QK_[A-Z_]+(_MAX)?$")
table = sorted(((n, v) for n, v in values.items()
                if not (skip.match(n) and n.startswith("QK_") and ("_MAX" in n or n in (
                    "QK_BASIC", "QK_MODS", "QK_MOD_TAP", "QK_LAYER_TAP", "QK_LAYER_MOD", "QK_TO",
                    "QK_MOMENTARY", "QK_DEF_LAYER", "QK_TOGGLE_LAYER", "QK_ONE_SHOT_LAYER",
                    "QK_ONE_SHOT_MOD", "QK_LAYER_TAP_TOGGLE", "QK_SWAP_HANDS", "QK_TAP_DANCE",
                    "QK_MAGIC", "QK_MIDI", "QK_SEQUENCER", "QK_JOYSTICK", "QK_PROGRAMMABLE_BUTTON",
                    "QK_AUDIO", "QK_STENO", "QK_MACRO", "QK_CONNECTION", "QK_LIGHTING", "QK_QUANTUM",
                    "QK_KB", "QK_USER", "QK_UNICODEMAP", "QK_UNICODE", "QK_UNICODEMAP_PAIR")))),
               key=lambda t: (t[1], len(t[0])))

lines = ["// Generated by scripts/generate_from_qmk.py from Keychron/qmk_firmware@2025q3. Do not edit.",
         "export const KEYCODE_TABLE: ReadonlyArray<readonly [string, number]> = ["]
lines += [f'  ["{n}", 0x{v:04X}],' for n, v in table]
lines.append("];")
(OUT / "qmk/keycodes.generated.ts").write_text("\n".join(lines) + "\n", newline="\n")
print(f"keycodes: {len(table)} names")

# ---------------------------------------------------------------- boards (every Keychron keyboard)
# One file per VIA definition (each ANSI/ISO/JIS, knob, RGB/white variant has its own USB product
# id): src/data/boards/<id>.json, loaded when that keyboard is plugged in, and an index of all of
# them (src/data/boards/index.json) that the Rust core embeds too.
KEYCHRON = QMK / "keyboards/keychron"
BOARDS_OUT = OUT / "data/boards"


def lenient_json(path: Path):
    """QMK's JSON files allow // comment lines and trailing commas."""
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"^\s*//.*$", "", text, flags=re.M)
    text = re.sub(r",(\s*[}\]])", r"\1", text)
    return json.loads(text)


def kle_keys(rows: list) -> list[dict]:
    """VIA's KLE layout → keys (kle-serial's rules, rotation included). Label 0 is "row,col",
    label 9 "e<n>" marks a knob. Decals (d) are drawings, not keys."""
    keys = []
    cur = {"x": 0.0, "y": 0.0, "r": 0.0, "rx": 0.0, "ry": 0.0}
    for row in rows:
        props: dict = {}
        for item in row:
            if isinstance(item, dict):
                if "r" in item:
                    cur["r"] = item["r"]
                if "rx" in item:
                    cur["rx"] = item["rx"]
                    cur["x"], cur["y"] = item["rx"], cur["ry"]
                if "ry" in item:
                    cur["ry"] = item["ry"]
                    cur["x"], cur["y"] = cur["rx"], item["ry"]
                cur["x"] += item.get("x", 0)
                cur["y"] += item.get("y", 0)
                props.update({k: item[k] for k in ("w", "h", "x2", "y2", "w2", "h2", "d") if k in item})
                continue
            w, h = props.get("w", 1), props.get("h", 1)
            label = item.split("\n")
            m = re.match(r"^\s*(\d+)\s*,\s*(\d+)\s*$", label[0])
            if m and not props.get("d"):
                key = {"row": int(m[1]), "col": int(m[2]), "x": cur["x"], "y": cur["y"], "w": w, "h": h}
                if "w2" in props or "h2" in props:
                    key.update({"x2": props.get("x2", 0), "y2": props.get("y2", 0), "w2": props.get("w2", w), "h2": props.get("h2", h)})
                if cur["r"]:
                    key.update({"r": cur["r"], "rx": cur["rx"], "ry": cur["ry"]})
                if len(label) > 9 and re.match(r"^e\d+$", label[9]):
                    key["encoder"] = int(label[9][1:])
                keys.append(key)
            cur["x"] += w
            props = {}
        cur["y"] += 1
        cur["x"] = cur["rx"]
    return keys


# USB product id → firmware folder, from every keyboard.json / info.json with one.
pid_folder: dict[int, Path] = {}
for f in sorted(list(KEYCHRON.glob("**/keyboard.json")) + list(KEYCHRON.glob("**/info.json"))):
    if "keymaps" in f.parts:
        continue
    try:
        pid = lenient_json(f).get("usb", {}).get("pid")
    except Exception:
        continue
    if pid:
        pid_folder.setdefault(int(pid, 16), f.parent)


def chain(folder: Path) -> list[Path]:
    """The folder and its parents up to the keyboard's own folder, top first."""
    out = []
    while folder != KEYCHRON and KEYCHRON in folder.parents:
        out.append(folder)
        folder = folder.parent
    return out[::-1]


def merged_info(folders: list[Path]) -> dict:
    info: dict = {}
    for d in folders:
        for name in ("info.json", "keyboard.json"):
            if (d / name).exists():
                try:
                    j = lenient_json(d / name)
                except Exception:
                    continue
                for k, v in j.items():
                    if isinstance(v, dict) and isinstance(info.get(k), dict):
                        info[k] = {**info[k], **v}
                    else:
                        info[k] = v
    return info


def c_led_config(folders: list[Path]):
    """g_led_config from the board's C files: [(row, col) or None, (x, y), flags] per LED."""
    for d in folders[::-1]:
        for c in sorted(d.glob("*.c")):
            src = c.read_text(encoding="utf-8", errors="replace")
            m = re.search(r"led_config_t\s+g_led_config\s*=\s*{(.*?)};", src, re.S)
            if not m:
                continue
            block = re.sub(r"//[^\n]*|/\*.*?\*/", "", m.group(1), flags=re.S)
            parts, depth, start = [], 0, 0
            for i, ch in enumerate(block):
                if ch == "{":
                    depth += 1
                    if depth == 1:
                        start = i + 1
                elif ch == "}":
                    depth -= 1
                    if depth == 0:
                        parts.append(block[start:i])
            if len(parts) != 3:
                continue
            key_of = {}
            for r, row in enumerate(re.findall(r"{([^{}]*)}", parts[0])):
                for col, cell in enumerate(x.strip() for x in row.split(",") if x.strip()):
                    if cell.isdigit():
                        key_of[int(cell)] = (r, col)
            points = [(int(x), int(y)) for x, y in re.findall(r"{\s*(\d+)\s*,\s*(\d+)\s*}", parts[1])]
            flags = [int(f) for f in re.findall(r"\d+", parts[2])]
            if not points:
                continue
            return [(key_of.get(i), p, flags[i] if i < len(flags) else 4) for i, p in enumerate(points)]
    return None


def led_map(folders: list[Path], info: dict, keys: list[dict]):
    """LEDs (key, x, y, flags), and where they came from: keyboard.json, the C file, or the layout."""
    layout = info.get("rgb_matrix", {}).get("layout") or info.get("led_matrix", {}).get("layout")
    if layout:
        leds = [(tuple(l["matrix"]) if "matrix" in l else None, (l["x"], l["y"]), l.get("flags", 4)) for l in layout]
        source = "json"
    else:
        leds, source = c_led_config(folders), "c"
    if leds:
        # Only LEDs under a key of this layout (a board's firmware covers every variant's keys).
        present = {(k["row"], k["col"]) for k in keys}
        out = [{"key": f"{k[0]},{k[1]}", "x": p[0], "y": p[1], "flags": f} for k, p, f in leds if k and tuple(k) in present]
        if out:
            return out, source
    # From the drawing: QMK computes positions the same way (key centres scaled to 224 × 64).
    plain = [k for k in keys if "encoder" not in k]
    if not plain:
        return [], "none"
    max_x = max(k["x"] + k["w"] / 2 for k in plain) or 1
    max_y = max(k["y"] + k["h"] / 2 for k in plain) or 1
    min_x = min(k["x"] + k["w"] / 2 for k in plain)
    min_y = min(k["y"] + k["h"] / 2 for k in plain)
    sx = 224 / max(max_x - min_x, 1)
    sy = 64 / max(max_y - min_y, 1)
    return [{"key": f"{k['row']},{k['col']}", "x": round((k["x"] + k["w"] / 2 - min_x) * sx),
             "y": round((k["y"] + k["h"] / 2 - min_y) * sy), "flags": 4} for k in plain], "layout"


def split_args(s: str) -> list[str]:
    """Top-level commas only: LT(1, KC_A) stays one argument."""
    out, depth, cur = [], 0, ""
    for ch in s:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def stock_keymap(folders: list[Path], info: dict, keys: list[dict]):
    """Keychron's own keymap (keymaps/keychron, else via, else default): the legends shown before the
    keyboard is plugged in. None when it can't be read."""
    km = None
    for name in ("keychron", "via", "default"):
        for d in folders[::-1]:
            if (d / "keymaps" / name / "keymap.c").exists():
                km = d / "keymaps" / name / "keymap.c"
                break
        if km:
            break
    if not km:
        return None
    src = re.sub(r"/\*.*?\*/", "", km.read_text(encoding="utf-8", errors="replace"), flags=re.S)
    src = re.sub(r"//[^\n]*", "", src)
    enum = re.search(r"enum\s+\w*\s*{([^}]*)}", src)
    layer_names = [re.sub(r"=.*", "", n).strip() for n in enum.group(1).split(",") if n.strip()] if enum else []
    layer_idx = {n: i for i, n in enumerate(layer_names)}
    defines = dict(re.findall(r"^#define\s+(\w+)\s+(.+?)\s*$", src, re.M))

    def resolve(tok: str) -> str:
        tok = defines.get(tok, tok)
        tok = {"_______": "KC_TRNS", "XXXXXXX": "KC_NO"}.get(tok, tok)
        return re.sub(r"\b([A-Z_][A-Z0-9_]*)\b", lambda m: str(layer_idx[m.group(1)]) if m.group(1) in layer_idx else m.group(1), tok)

    layouts = {**info.get("layouts", {}), **{a: info.get("layouts", {}).get(t) for a, t in info.get("layout_aliases", {}).items()}}
    layers = []
    for m in re.finditer(r"\[\s*(\w+)\s*\]\s*=\s*(LAYOUT\w*)\s*\(", src):
        # The macro's arguments, up to its closing parenthesis.
        i, depth = m.end(), 1
        while depth and i < len(src):
            depth += {"(": 1, ")": -1}.get(src[i], 0)
            i += 1
        args = [resolve(a) for a in split_args(src[m.end():i - 1])]
        layout = layouts.get(m.group(2))
        if not layout or len(layout.get("layout", [])) != len(args):
            return None
        by_key = {f"{l['matrix'][0]},{l['matrix'][1]}": a for l, a in zip(layout["layout"], args)}
        layers.append((m.group(1), [by_key.get(f"{k['row']},{k['col']}", "") for k in keys]))
    if not layers:
        return None
    knobs = []
    for name, _ in layers:
        e = re.search(rf"\[\s*{name}\s*\]\s*=\s*{{(.*?)}}\s*,?\s*(?=\[|}})", src, re.S)
        knobs.append([list(p) for p in re.findall(r"ENCODER_CCW_CW\(\s*(\w+)\s*,\s*(\w+)\s*\)", e.group(1))] if e else [])
    names = [n for n, _ in layers]
    return {
        # Keychron's Win/Mac switch: Windows' base layer is the default one on Windows.
        "defaultLayer": names.index("WIN_BASE") if "WIN_BASE" in names else 0,
        "layers": [l for _, l in layers],
        "encoders": knobs,
    }


def rgb_center(folders: list[Path], info: dict) -> list[int]:
    for part in ("rgb_matrix", "led_matrix"):
        c = info.get(part, {}).get("center_point")
        if c:
            return list(c)
    for d in folders[::-1]:
        cfg = d / "config.h"
        if cfg.exists():
            m = re.search(r"#define\s+(?:RGB|LED)_MATRIX_CENTER\s*{\s*(\d+)\s*,\s*(\d+)\s*}", cfg.read_text(errors="replace"))
            if m:
                return [int(m[1]), int(m[2])]
    return [112, 32]


# Keychron's own keys: VIA's customKeycodes list, entry i being QK_KB_0 + i. It differs per board
# (wireless keys, OS switch, profiles…), so each board carries its own; these are their QMK names.
KEYCHRON_KEYS = {
    "left option": "KC_LOPTN", "right option": "KC_ROPTN", "left cmd": "KC_LCMMD", "right cmd": "KC_RCMMD",
    "mission control": "KC_MCTRL", "launchpad": "KC_LNPAD", "launch pad": "KC_LNPAD", "task view": "KC_TASK",
    "file explorer": "KC_FILE", "screen shot": "KC_SNAP", "cortana": "KC_CTANA", "siri": "KC_SIRI",
    "bluetooth host 1": "BT_HST1", "bluetooth host 2": "BT_HST2", "bluetooth host 3": "BT_HST3",
    "2.4g": "P2P4G", "battery level": "BAT_LVL", "effect speed+": "BL_SPI", "effect speed-": "BL_SPD",
    "profile 1": "PROF1", "profile 2": "PROF2", "profile 3": "PROF3", "os toggle": "OS_TOGGL",
    "os_mac": "OS_MAC", "os_win": "OS_WIN",
}
# Long names keymaps use for the same keys.
KEYCHRON_ALIASES = {
    "KC_MAC_MISSION_CONTROL": "KC_MCTRL", "KC_MAC_LAUCHPAD": "KC_LNPAD", "KC_MAC_LAUNCHPAD": "KC_LNPAD",
    "KC_WIN_TASK_VIEW": "KC_TASK", "KC_WIN_FILE_EXPLORER": "KC_FILE", "KC_MAC_SCREEN_SHOT": "KC_SNAP",
    "KC_WIN_CORTANA": "KC_CTANA", "KC_MAC_SIRI": "KC_SIRI",
}


def custom_keycodes(via: dict) -> list[dict]:
    out = []
    for c in via.get("customKeycodes") or []:
        title = c.get("name", "")
        name = KEYCHRON_KEYS.get(title.lower()) or "KC_" + re.sub(r"[^A-Z0-9]+", "_", title.upper()).strip("_")
        out.append({"name": name, "label": c.get("shortName") or title, "title": c.get("title") or title})
    return out


def with_custom_values(keymap, custom: list[dict]):
    """Keychron's key names in the stock keymap → this board's values (QK_KB_0 + i); US shifted
    names → their values."""
    if not keymap:
        return keymap
    value = {c["name"]: f"0x{values['QK_KB'] + i:04X}" for i, c in enumerate(custom)}
    value.update({n: f"0x{v:04X}" for n, v in us_shifted.items()})

    def fix(tok: str) -> str:
        return re.sub(r"\b[A-Z][A-Z0-9_]*\b", lambda m: value.get(KEYCHRON_ALIASES.get(m.group(0), m.group(0)), m.group(0)), tok)

    keymap["layers"] = [[fix(t) for t in layer] for layer in keymap["layers"]]
    keymap["encoders"] = [[[fix(t) for t in knob] for knob in layer] for layer in keymap["encoders"]]
    return keymap


# LED matrix effects (white backlights), in QMK's enum order (led_matrix_effects.inc and each
# animation's LED_MATRIX_EFFECT lines). A board numbers only the ones it enables, from 1.
LED_EFFECT_ORDER: list[str] = []
_lm = QMK / "quantum/led_matrix/animations"
for inc in re.findall(r'#include "(\w+\.h)"', (_lm / "led_matrix_effects.inc").read_text()):
    LED_EFFECT_ORDER += re.findall(r"LED_MATRIX_EFFECT\((\w+)\)", (_lm / inc).read_text())
LED_EFFECT_NAMES = {
    "SOLID": "Solid", "ALPHAS_MODS": "Alphas & mods", "BREATHING": "Breathing", "BAND": "Band",
    "BAND_PINWHEEL": "Band pinwheel", "BAND_SPIRAL": "Band spiral", "CYCLE_LEFT_RIGHT": "Cycle left right",
    "CYCLE_UP_DOWN": "Cycle up down", "CYCLE_OUT_IN": "Cycle out in", "DUAL_BEACON": "Dual beacon",
    "SOLID_REACTIVE_SIMPLE": "Reactive simple", "SOLID_REACTIVE_WIDE": "Reactive wide",
    "SOLID_REACTIVE_MULTIWIDE": "Reactive multiwide", "SOLID_REACTIVE_CROSS": "Reactive cross",
    "SOLID_REACTIVE_MULTICROSS": "Reactive multicross", "SOLID_REACTIVE_NEXUS": "Reactive nexus",
    "SOLID_REACTIVE_MULTINEXUS": "Reactive multinexus", "SOLID_SPLASH": "Splash", "SOLID_MULTISPLASH": "Multisplash",
    "WAVE_LEFT_RIGHT": "Wave left right", "WAVE_UP_DOWN": "Wave up down",
}


def led_effects(info: dict) -> list:
    """[name, id] of a white board's LED matrix effects: None, then the enabled ones in enum order."""
    enabled = {k.upper() for k, on in info.get("led_matrix", {}).get("animations", {}).items() if on}
    ids = [e for e in LED_EFFECT_ORDER if e in enabled]
    return [["None", 0]] + [[LED_EFFECT_NAMES.get(e, e.title()), i + 1] for i, e in enumerate(ids)]


def effect_options(menus) -> list | None:
    found = []

    def walk(node):
        if isinstance(node, dict):
            c = node.get("content")
            if isinstance(c, list) and len(c) == 3 and c[0] == "id_qmk_rgb_matrix_effect" and node.get("options"):
                found.append(node["options"])
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    walk(menus)
    return found[0] if found else None


def effect_showif(menus, control: str) -> str | None:
    """The `showIf` of a control (e.g. the effect speed), as VIA writes it."""
    found = []

    def walk(node):
        if isinstance(node, dict):
            c = node.get("content")
            if isinstance(c, list) and len(c) == 3 and c[0] == control:
                found.append(node.get("showIf"))
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    walk(menus)
    return found[0] if found else None


def showif_ids(expr: str | None, ids: list[int]) -> list[int]:
    """Which effect ids a VIA `showIf` accepts. The grammar is `{id_qmk_rgb_matrix_effect} OP N`
    joined by && / || with parentheses; translating it to Python and evaluating is exact enough
    for a build script, and keeps the app from carrying a VIA expression parser."""
    if not expr:
        return []
    py = expr.replace("{id_qmk_rgb_matrix_effect}", "e").replace("&&", " and ").replace("||", " or ")
    out = []
    for e in ids:
        try:
            if eval(py, {"__builtins__": {}}, {"e": e}):  # noqa: S307 - a build script, our own string
                out.append(e)
        except Exception:
            return []
    return out


BOARDS_OUT.mkdir(parents=True, exist_ok=True)
for old in BOARDS_OUT.glob("*.json"):
    old.unlink()
index, seen, stats = [], set(), {"json": 0, "c": 0, "layout": 0, "none": 0, "keymap": 0}
# "_via" before "_launcher" (the C3 Pro 8K ships both, same board).
via_files = sorted(KEYCHRON.glob("**/via_json/*.json"), key=lambda p: (p.parent.as_posix(), "launcher" in p.stem, p.stem))
for f in via_files:
    via = lenient_json(f)
    vid, pid = int(via["vendorId"], 16), int(via["productId"], 16)
    if (vid, pid) in seen:
        continue
    seen.add((vid, pid))
    board_id = re.sub(r"_(via|launcher)$", "", f.stem)
    # Unique ids: Keychron reuses names across models (the Q2 Max's files are "q2_ansi_encoder"…).
    kb = f.parent.parent.name
    if not board_id.startswith(kb + "_"):
        board_id = kb + "_" + board_id.split("_", 1)[-1]
    # A key outside the matrix is a mistake in the definition (one JIS layout has one): left out.
    keys = [k for k in kle_keys(via["layouts"]["keymap"]) if k["row"] < via["matrix"]["rows"] and k["col"] < via["matrix"]["cols"]]
    folder = pid_folder.get(pid)
    folders = chain(folder) if folder else [f.parent.parent]
    info = merged_info(folders)
    effects = effect_options(via.get("menus", []))
    features = info.get("features", {})
    lighting = "rgb" if effects or features.get("rgb_matrix") else "white" if features.get("led_matrix") else "none"
    if lighting == "white":
        effects = led_effects(info)
    # Which effects use the speed and the colour, from the VIA definition's own showIf rules (the
    # app used to hard-code the V6 8K's). White boards: the speed is used by every effect but Solid.
    effect_ids = [e[1] for e in effects or []]
    if lighting == "white":
        speed_ids = [e for e in effect_ids if e > 0 and dict(effects).get(e) != "Solid"]
        color_ids = []
    else:
        speed_ids = showif_ids(effect_showif(via.get("menus", []), "id_qmk_rgb_matrix_effect_speed"), effect_ids)
        color_ids = showif_ids(effect_showif(via.get("menus", []), "id_qmk_rgb_matrix_color"), effect_ids)
    leds, source = led_map(folders, info, keys) if lighting != "none" else ([], "none")
    stats[source] += 1
    custom = custom_keycodes(via)
    keymap = with_custom_values(stock_keymap(folders, info, keys), custom) if folder else None
    stats["keymap"] += keymap is not None
    encoders = len({k["encoder"] for k in keys if "encoder" in k})
    board = {
        "id": board_id,
        "name": via["name"],
        "vid": vid,
        "pid": pid,
        "matrix": via["matrix"],
        "encoders": encoders,
        "firmware": folder.relative_to(QMK / "keyboards").as_posix() if folder else None,
        "lighting": lighting,
        # Flashing: at32-dfu, stm32-dfu, wb32-dfu… (QMK's bootloader name).
        "bootloader": info.get("bootloader"),
        "effects": effects or [],
        "mix": any(e[1] == 24 for e in effects or []),
        # Which effects use the speed and the colour (from the VIA definition's showIf rules).
        "speedEffects": speed_ids,
        "colorEffects": color_ids,
        "center": rgb_center(folders, info),
        "customKeycodes": custom,
        "keys": keys,
        "leds": leds,
        "keymap": keymap,
    }
    (BOARDS_OUT / f"{board_id}.json").write_text(json.dumps(board, separators=(",", ":")), encoding="utf-8", newline="\n")
    index.append({k: board[k] for k in ("id", "name", "vid", "pid", "encoders", "firmware", "lighting", "mix", "bootloader")}
                 | {"rows": via["matrix"]["rows"], "cols": via["matrix"]["cols"],
                    # The default layer (Keychron's Win base), for the app's fallback when the
                    # keyboard can't say which layer it is on.
                    "defaultLayer": (keymap or {}).get("defaultLayer", 0)})
index.sort(key=lambda b: b["name"].lower())
(BOARDS_OUT / "index.json").write_text(json.dumps(index, indent=1), encoding="utf-8", newline="\n")
print(f"boards: {len(index)} (LEDs from keyboard.json {stats['json']}, C {stats['c']}, layout {stats['layout']}, none {stats['none']}; stock keymap {stats['keymap']})")
